### ISSUE TITLE
Documentation question.

### ISSUE THREAD

**Issue by hguillermo** [rishabhmhjn/helios#4]
Hi,

I saw this in the documentation:
var solrdoc = new helios.document();
solrdoc.addField('field_name1', 'value1');
solrdoc.addField('field_name2', 'value2');

solr_client.addDoc(solrdoc, true, function(err) {
  if (err) console.log(err);
});

I think that should use setField instead of addField right? Let me know,

Thanks,

Harry

**Comment by rishabhmhjn** [comment]
Yes you are right. It should be `setField`. This needs to be fixed.

Just in case, I explain the use of `setField` and `addField`.
- In case there is a field with `multiValued=true` in solr scheme, `addField` should be used
- For everything else, there is `setField`

**Comment by hguillermo** [comment]
I think you mean setMultiValue and not addField? right?
 
Harry 

Github: hguillermo 
SkypeId: harryguillermo

**Comment by rishabhmhjn** [comment]
Yes, `setMultiValue` should be used for that purpose, fields with `multiValued=true`.

But, `setMultiValue` uses `addField` to add information to the document. So `addField` may not be used outside the library.

> https://github.com/rishabhmhjn/helios/blob/bda0d4e2c03037a6cd65dba5f018f3d1a8fabb15/lib/document.js#L54

``` js
  this.setMultiValue = function(key, value, boost) {
    this.addField(key, value, boost);
    return this;
  };
```

**Comment by hguillermo** [comment]
Yeah, that sounds right. :)
 
Harry 

Github: hguillermo 
SkypeId: harryguillermo
