### ISSUE TITLE
nlogger is required but only listed as a devDependency

### ISSUE THREAD

**Issue by mshick** [rishabhmhjn/helios#6]
The require()s in lib/client.js, queryBuilder, and so on make nlogger a requirement to use helios at all, not just a dev dependency.

Maybe you should find a way to make nlogger optional, or, move it up to the regular dependencies so it gets installed on a normal "npm install helios"

**Comment by rishabhmhjn** [comment]
I'm sorry for the late response.
If it's giving an error, can you fix it and send a pull request?
I'll merge it afterwards

**Comment by Trott** [comment]
This looks like it was resolved by  https://github.com/rishabhmhjn/helios/commit/474850b5d9b475fd8a33d3c7b111fbdbaa0aaaac#diff-50cfa59973c04321b5da0c6da0fdf4fe. If so, can you close this?
